export const RESET_STATE = "RESET_STATE";
export const TOGGLE_FORM = "TOGGLE_FORM";

export const CHARACTERS_REQUEST = "CHARACTERS_REQUEST";
export const CHARACTERS_SUCCESS = "CHARACTERS_SUCCESS";
export const CHARACTERS_FAILED = "CHARACTERS_FAILED";

export const UPDATE_SEARCH_CRITERIA = "UPDATE_SEARCH_CRITERIA";

export const UPDATE_CHARACTER_NAME = "UPDATE_CHARACTER_NAME";
export const UPDATE_CHARACTER_DESCRIPTION = "UPDATE_CHARACTER_DESCRIPTION";
export const UPDATE_CHARACTER_URL = "UPDATE_CHARACTER_URL";

export const CHARACTERS_CREATE_REQUEST = "CHARACTERS_CREATE_REQUEST";
export const CHARACTERS_CREATE_SUCCESS = "CHARACTERS_CREATE_SUCCESS";
export const CHARACTERS_CREATE_FAILED = "CHARACTERS_CREATE_FAILED";

export const CHARACTERS_DELETE_REQUEST = "CHARACTERS_DELETE_REQUEST";
export const CHARACTERS_DELETE_SUCCESS = "CHARACTERS_DELETE_SUCCESS";
export const CHARACTERS_DELETE_FAILED = "CHARACTERS_DELETE_FAILED";
